name: 'actions-code-deploy'
inputs:
  application-name:
    required: true
  deployment-group-name:
    required: true
  output-directory:
    required: true
  s3-bucket:
    required: true
  environment:
    required: true
  code-deploy-strategy:
    required: true
runs:
  using: "composite"
  steps:     
      - run: aws deploy push --application-name  ${{inputs.application-name}} --s3-location s3://${{inputs.s3-bucket}}/${{inputs.application-name}}.zip --source ${{inputs.output-directory}} --ignore-hidden-files
        shell: powershell       
      - run: echo aws deploy create-deployment --application-name ${{inputs.application-name}} --s3-location bucket=${{inputs.s3-bucket}},key=${{inputs.application-name}}.zip,bundleType=zip --deployment-group-name ${{inputs.deployment-group-name}} --deployment-config-name ${{inputs.code-deploy-strategy}}
        shell: powershell
      - run: aws deploy create-deployment --application-name ${{inputs.application-name}} --s3-location bucket=${{inputs.s3-bucket}},key=${{inputs.application-name}}.zip,bundleType=zip --deployment-group-name ${{inputs.deployment-group-name}} --deployment-config-name ${{inputs.code-deploy-strategy}}
        shell: powershell
